### ISSUE TITLE
Test Terraform code with latest version and upgrade tf to support

### ISSUE THREAD

**Issue by ineffyble** [rabblerouser/rabblerouser-infra#13]
`tf` currently won't run with the latest stable Terraform release (0.11.3), as it requires 0.10. Compatibility with the latest major release of Terraform should be tested, and tf updated to require 0.11 if there is no issues.

**Comment by camjackson** [comment]
Looking at the release notes I don't think any of the breaking changes will affect us, although the new plan/apply behaviour might allow us to simplify the `tf` script somewhat.

I'll test it out tomorrow.
