### ISSUE TITLE
Add a proper VPC for better security

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/rabblerouser-infra#6]
Right now we use the default VPC, which has everything open by default (I think?) We do have security groups to lock things down. So, e.g. the database can only be accessed from the EC2 server. It would be good to lock things down from a networking POV though.

**Comment by tomsulston** [comment]
Use Kief's magic Amazon-spinning up amazingness.

**Comment by camjackson** [comment]
I think we can just close this for now, unless anyone has a reason why the default VPC isn't a good option. The security groups should be fine.
