### ISSUE TITLE
Use docker for deployments

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/rabblerouser-infra#8]
Right now we install the app onto servers something like this (plus a few other things):
- install node
- clone the rabblerouser-core source code
- npm install (which also does compilation, etc)
- npm start

Rather than build the app live in production, we should produce a proper build artefact in our CI pipeline, and deploy that onto our servers.

Docker is great for this, and in fact we're already [publishing an image](https://hub.docker.com/r/rabblerouser/rabblerouser-core/) to the docker hub. For this issue, we should:

- [x] Remove the git/node/npm stuff mentioned above
- [x] Install docker
- [x] Pull down the latest docker image (or maybe a configurable version)
- [x] Start a container from that image, making sure it logs, restarts on failure, etc

Essentially it's an overhaul of [this file](https://github.com/rabblerouser/rabblerouser-infra/blob/master/ansible/roles/core-app/tasks/main.yml) to use docker.

**Comment by camjackson** [comment]
Not sure if this is helpful or not, but here's a docker command I've been using when testing stuff out locally:

`docker run --rm --name rabblerouser-core -e DATABASE_URL="$DATABASE_URL" -e SESSION_SECRET="$SESSION_SECRET" -p 3000:3000 rabblerouser/rabblerouser-core`

**Comment by pameck** [comment]
An overlook to what our deployment will look like once we play and finish this card.

![whatsapp image 2017-01-07 at 4 59 18 pm 1](https://cloud.githubusercontent.com/assets/3664374/21739866/c1d5b0d6-d4fb-11e6-810d-d7a4ef9ad9f2.jpeg)
